// flow-typed signature: 406bc6875072c6c07edd5865d885a4ac
// flow-typed version: <<STUB>>/animate.css-react_vx.x.x/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animate.css-react/build/Animate' {
  declare module.exports: any;
}

declare module 'animate.css-react/build/libs/React16CSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'animate.css-react/build/libs/React16CSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'animate.css-react/build/libs/React16TransitionEvents' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/animations' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/App' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/Code' {
  declare module.exports: any;
}

declare module 'animate.css-react/example' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/List' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/Select' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/server' {
  declare module.exports: any;
}

declare module 'animate.css-react/example/webpack.config' {
  declare module.exports: any;
}

declare module 'animate.css-react/src/Animate' {
  declare module.exports: any;
}

declare module 'animate.css-react/src/libs/React16CSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'animate.css-react/src/libs/React16CSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'animate.css-react/src/libs/React16TransitionEvents' {
  declare module.exports: any;
}

declare module 'animate.css-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animate.css-react/build/Animate.js' {
  declare module.exports: $Exports<'animate.css-react/build/Animate'>;
}
declare module 'animate.css-react/build/libs/React16CSSTransitionGroup.js' {
  declare module.exports: $Exports<'animate.css-react/build/libs/React16CSSTransitionGroup'>;
}
declare module 'animate.css-react/build/libs/React16CSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'animate.css-react/build/libs/React16CSSTransitionGroupChild'>;
}
declare module 'animate.css-react/build/libs/React16TransitionEvents.js' {
  declare module.exports: $Exports<'animate.css-react/build/libs/React16TransitionEvents'>;
}
declare module 'animate.css-react/example/animations.js' {
  declare module.exports: $Exports<'animate.css-react/example/animations'>;
}
declare module 'animate.css-react/example/App.js' {
  declare module.exports: $Exports<'animate.css-react/example/App'>;
}
declare module 'animate.css-react/example/Code.js' {
  declare module.exports: $Exports<'animate.css-react/example/Code'>;
}
declare module 'animate.css-react/example/index' {
  declare module.exports: $Exports<'animate.css-react/example'>;
}
declare module 'animate.css-react/example/index.js' {
  declare module.exports: $Exports<'animate.css-react/example'>;
}
declare module 'animate.css-react/example/List.js' {
  declare module.exports: $Exports<'animate.css-react/example/List'>;
}
declare module 'animate.css-react/example/Select.js' {
  declare module.exports: $Exports<'animate.css-react/example/Select'>;
}
declare module 'animate.css-react/example/server.js' {
  declare module.exports: $Exports<'animate.css-react/example/server'>;
}
declare module 'animate.css-react/example/webpack.config.js' {
  declare module.exports: $Exports<'animate.css-react/example/webpack.config'>;
}
declare module 'animate.css-react/src/Animate.js' {
  declare module.exports: $Exports<'animate.css-react/src/Animate'>;
}
declare module 'animate.css-react/src/libs/React16CSSTransitionGroup.js' {
  declare module.exports: $Exports<'animate.css-react/src/libs/React16CSSTransitionGroup'>;
}
declare module 'animate.css-react/src/libs/React16CSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'animate.css-react/src/libs/React16CSSTransitionGroupChild'>;
}
declare module 'animate.css-react/src/libs/React16TransitionEvents.js' {
  declare module.exports: $Exports<'animate.css-react/src/libs/React16TransitionEvents'>;
}
declare module 'animate.css-react/webpack.config.js' {
  declare module.exports: $Exports<'animate.css-react/webpack.config'>;
}
