// flow-typed signature: 919a4d12bb4c786ea70a2541aa3830a5
// flow-typed version: <<STUB>>/react-animate.css_vx.x.x/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-animate.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-animate.css/example/animations' {
  declare module.exports: any;
}

declare module 'react-animate.css/example/App' {
  declare module.exports: any;
}

declare module 'react-animate.css/example/Code' {
  declare module.exports: any;
}

declare module 'react-animate.css/example' {
  declare module.exports: any;
}

declare module 'react-animate.css/example/List' {
  declare module.exports: any;
}

declare module 'react-animate.css/example/Select' {
  declare module.exports: any;
}

declare module 'react-animate.css/example/server' {
  declare module.exports: any;
}

declare module 'react-animate.css/lib/Animate' {
  declare module.exports: any;
}

declare module 'react-animate.css/modules/Animate' {
  declare module.exports: any;
}

declare module 'react-animate.css/umd/Animate' {
  declare module.exports: any;
}

declare module 'react-animate.css/umd/Animate.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-animate.css/example/animations.js' {
  declare module.exports: $Exports<'react-animate.css/example/animations'>;
}
declare module 'react-animate.css/example/App.js' {
  declare module.exports: $Exports<'react-animate.css/example/App'>;
}
declare module 'react-animate.css/example/Code.js' {
  declare module.exports: $Exports<'react-animate.css/example/Code'>;
}
declare module 'react-animate.css/example/index' {
  declare module.exports: $Exports<'react-animate.css/example'>;
}
declare module 'react-animate.css/example/index.js' {
  declare module.exports: $Exports<'react-animate.css/example'>;
}
declare module 'react-animate.css/example/List.js' {
  declare module.exports: $Exports<'react-animate.css/example/List'>;
}
declare module 'react-animate.css/example/Select.js' {
  declare module.exports: $Exports<'react-animate.css/example/Select'>;
}
declare module 'react-animate.css/example/server.js' {
  declare module.exports: $Exports<'react-animate.css/example/server'>;
}
declare module 'react-animate.css/lib/Animate.js' {
  declare module.exports: $Exports<'react-animate.css/lib/Animate'>;
}
declare module 'react-animate.css/modules/Animate.js' {
  declare module.exports: $Exports<'react-animate.css/modules/Animate'>;
}
declare module 'react-animate.css/umd/Animate.js' {
  declare module.exports: $Exports<'react-animate.css/umd/Animate'>;
}
declare module 'react-animate.css/umd/Animate.min.js' {
  declare module.exports: $Exports<'react-animate.css/umd/Animate.min'>;
}
