// flow-typed signature: d22dfeb1e2ea31c4fb5fae165022b152
// flow-typed version: <<STUB>>/animate.css/animate.css_vx.x.x/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css/animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css/animate.css' {
  declare module.exports: any;
}
